version: '3.8'

services:
  transcription-service:
    image: transcription-service
    network_mode: 'host'
    ports:
      - '5051:5051'
    volumes:
      - /home/josh/dev/acai.so/server/.env:/app/.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']
    environment:
      NVIDIA_VISIBLE_DEVICES: all

  acai:
    image: acai
    network_mode: 'host'
    ports:
      - '5050:5050'
    volumes:
      - /home/josh/dev/acai.so/server/.env:/app/.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']
    environment:
      NVIDIA_VISIBLE_DEVICES: all
